name: fireredvad_example
description: Example app demonstrating fireredvad streaming Voice Activity Detection.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fireredvad:
    path: ../
  record: ^6.2.0
  permission_handler: ^12.0.1
  just_audio: ^0.10.5
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/weights.bin
    - assets/cmvn.json
